### ISSUE TITLE
DataFrame Explorer uses a wrong port

### ISSUE THREAD

**Issue by hanase** [UDST/urbansim#145]
The DataFrame Explorer is retrieving data from the default port (8765) instead of using the user-defined one passed via the port argument.

**Comment by fscottfoti** [comment]
@hanase can you try the dataframe-explorer-port branch?   I haven't tested it but there were only a few changes...

https://github.com/synthicity/urbansim/pull/146/files

**Comment by hanase** [comment]
I'm getting this error:
  File "/Users/hana/synthicity/urbansim/urbansim/maps/dframe_explorer.py", line 117, in start
    root = "http://%s:%d/" % (host, port)
TypeError: %d format: a number is required, not str

**Comment by fscottfoti** [comment]
Are you passing the port as a string?  It should be an int.  I can cast to an int to be safe.

**Comment by jiffyclub** [comment]
If the port is coming in from the command line: command line arguments are always strings unless otherwise specified.

**Comment by hanase** [comment]
Yes - that's what I'm doing - it's coming from a command line. But I can cast it before passing in.

**Comment by hanase** [comment]
OK, when I cast the port, it's working. Thanks a lot Fletcher!

**Comment by fscottfoti** [comment]
You bet!
