### ISSUE TITLE
Python 2, 3, or Both?

### ISSUE THREAD

**Issue by mattayes** [UDST/urbansim#152]
I can't find any mention of the Python version(s) you can use with urbansim.

**Comment by jiffyclub** [comment]
I think it'll only run on Python 2 at the moment, but I also don't think it'd be a huge chore to update all the print statements to work on Python 3. There's nothing preventing UrbanSim itself from working on Python 3. However, if you also need to use Pandana that only works on Python 2 and I don't know when/if it will be updated.

**Comment by pksohn** [comment]
FYI We're finally working on this, as we just released a new version of Pandana with Python 3 compatibility.

**Comment by pksohn** [comment]
Python 3.5 now compatible with #192. We will add information to docs as well.
