### ISSUE TITLE
problem in segmented transition model and pandas 

### ISSUE THREAD

**Issue by bridwell** [UDST/urbansim#156]
I'm having issues with a segmented tabular transition model using pandas 0.17.0. The issue seems to occur when calling df.query in the urbansim.models.util.apply_filter_query method. Sometimes when called, no results are returned even when the query is valid. The issue is intermittent, so different segments are affected across different runs. 

Has anyone experienced anything like this or had issues with DataFrame.query? The same code and data works fine in pandas 0.13.1. 

thanks,
scott

**Comment by fscottfoti** [comment]
I haven't seen that issue, but have noticed that the UrbanSim tests are now failing in the transition model.  Matt and I assumed it was a Pandas change so this could be related...

**Comment by bridwell** [comment]
Thanks Fletcher for the response. After more testing, we've found the following:

1) The does not occur on Windows 7 machines.

2) The issue does occur on Window 8.1, Windows Server 2012 R2 and Windows 10.

3) In the query call, setting the engine to python (e.g. df.quey("a == 2", engine='python'), fixes the issue. So it seems the problem is perhaps with numexpr not pandas per se. We've created an issue here:  https://github.com/pydata/pandas/issues/12055

I'm not sure how to rectify this. Perhaps there could be an urbnansim global property that sets query evaluation engine? 

thanks,
scott

**Comment by bridwell** [comment]
It looks like the issue is with numexp v 2.4.4. Upgrading to v.2.4.6 fixes this.

**Comment by fscottfoti** [comment]
Good detective work!

**Comment by waddell** [comment]
Very helpful, Scott!
