### ISSUE TITLE
Dose max_dua account for resratio?

### ISSUE THREAD

**Issue by Eh2406** [UDST/urbansim#166]
We are testing a pro forma model. We got it running without max_dua. Then we added a max_dua column. No more non res, nor mixed use construction! looking into it we had set the max_dua = 0 for non res parcels.

I expected that max_dua = 0 would lead to only non res construction.

I observed that max_dua = 0 lead to no construction.

------------------------

My theory:

max_far_from_dua does not account for resratio. There for any building has max_far_from_dua > 0. Thus no new construction.

**Comment by fscottfoti** [comment]
Hmm, good question.  So the tricky part is that on the residential side, in San Francisco we often have density limits set for residential using max_far, so it's not like max_dua is for res and max_far is for non-res.  This led me to create an equivalency as best as I could to limit the number of units using max_far based on average unit sizes, building efficiency etc.

So there's a good reason to have both limits if it's a residential building, but I don't see the max_dua is ever useful on the non-res side.  To my mind, I wasn't expecting a max_dua if the building was non-residential, and my first instinct is that that should actually be an error.  What do you think?

For mixed use, the ratio is set for a given building type and I think a max_dua of 0 means that a mixed use building type can't be built, so in that sense the result there seems to be correct.  I would not expect the developer to create a "mixed use" building type with no residential as that might be confusing when tabulating outcome metrics and such.

In practice, in the Bay Area model we decided to not let the developer do the equivalence of max_dua and max_far - that seemed like special logic to us, so we decided to compute the result in our code and then pass in only one of the density limits for any given building type.  That way you have total control of what's happening and can map the inputs very clearly.  It is certainly not required that you let the developer model equate max_dua, max_far, and max_height for you if you don't like the logic that lives there now.  My guess is that there is no "one size fits all" solution in interpreting zoning across regions, especially when those regions are in different counties.

**Comment by Eh2406** [comment]
Sorry if I came across as dismissive. I love that it can optimize with multiple constraints, even when it takes a lot of work to convert between them. I can only imagine how hard it was to get it right the first time; thank you. I was only suggesting a small improvement:
https://github.com/Eh2406/urbansim/commit/72a78e67c97aa75474a70bfd396d7e0210d10b35

If it is pure res, than the current calck is correct.

If we have a mixed use with .5 res and max dua of 3 than the current calculation is incorrect. The current calculation determines the max_far if 100% or usable space is used for residential, but only 50% of the building is residential. So we can build a larger building. (If this is the active constraint.)

In the pur non res case, we can raise an error (explicit is better than implicit) if you want. Or we can ignore 'max_dua' if resratio == 0. No amount of non res construction will fall a fawell of 'max_dua'. I can add a comment to change from

    if 'max_dua' in df.columns:

to 
  
    if 'max_dua' in df.columns and resratio > 0:

to save time, make that clear, and avoid dividing by 0, but it will end up the same.

**Comment by fscottfoti** [comment]
No problem, always good to get feedback!!

I see your point here.  If you do pass a max_dua the current code will assume that 100% of the building is residential when computing using that limit, and that's not correct.  I would definitely hope that we'd also pass in a max_far for a mixed use building, rather than taking an implied density from the max_dua and resratio, but I agree that this patch is better than the logic there now.

I think it would be fine to just add the `and resratio > 0` - personally I like that just fine.

Good catch!!
