### ISSUE TITLE
Exception raised in developer if no feasible buildings

### ISSUE THREAD

**Issue by moritz-kirmse-forcity** [UDST/urbansim#174]
If feasibility for all buildings of a given form is n/a, developer.pick raises a ValueError exception.

Suggested bugfix in [developer:64](https://github.com/UDST/urbansim/blob/master/urbansim/developer/developer.py#L64):

was:

```
        mu = self._max_form(f, "max_profit")
        indexes = [tuple(x) for x in mu.reset_index().values]
```

should be:

```
        if len(f) > 0:
            mu = self._max_form(f, "max_profit")
            indexes = [tuple(x) for x in mu.reset_index().values]
        else:
            indexes = []
```

**Comment by fscottfoti** [comment]
Looks good to me - want to submit a PR?
