### ISSUE TITLE
Change in predict() in statsmodels 0.8 no longer drops NaN values in returned Series

### ISSUE THREAD

**Issue by pksohn** [UDST/urbansim#185]
Statsmodels released 0.8.0 last month. Part of the [changes](http://www.statsmodels.org/stable/release/version0.8.html) are:

> Backwards incompatible changes and deprecations
> * predict now returns a pandas Series if the exog argument is a DataFrame, including missing/NaN values

We use the statsmodels `predict` method in the regression module. Previously, any missing/NaN values passed to the exog argument would be removed from the returned Series. This would result in a mismatch between the lengths of the input data and the predicted data, raising the `ModelEvaluationError` [here](https://github.com/UDST/urbansim/blob/master/urbansim/models/regression.py#L90). Looks like with this change, the predicted data comes back the same length with NaN values included, so the assertion fails.

Places where a parcel model like `urbansim_defaults` would interact with this include:
- [Hedonic simulation](https://github.com/UDST/urbansim_defaults/blob/master/urbansim_defaults/utils.py#L274)
- [Location choice simulation](https://github.com/UDST/urbansim_defaults/blob/master/urbansim_defaults/utils.py#L451)
In both of these examples, the `urbansim_defaults` code does a check for NaN values in the input DataFrame before going into the predict() method, so behavior should not change.

The easiest fix for this is probably just to extend the `predict` function in `regression.py` to drop rows with NaN values in the returned Series, only if it's a Series (seems like this change to statsmodels only applies to input DataFrames/output Series. NDarrays would be unchanged). The current [code looks like this](https://github.com/UDST/urbansim/blob/master/urbansim/models/regression.py#L87):

```
sim_data = model_fit.predict(df)
```

This is the proposed change that should keep the old behavior is:

```
sim_data = model_fit.predict(df)
if isinstance(sim_data, pd.Series):
    sim_data.dropna(inplace=True)
```

I'll issue a PR with the above change if folks don't have other ideas, but wanted to raise the issue first in case there's something I haven't considered.

**Comment by fscottfoti** [comment]
Hmm, I think that wasn't a preferred outcome of statsmodels but just a test written to note when the behavior changed.  I think it's quite possible that the new behavior is better (not dropping rows with nans) and that the test should be changed.  I always was confused when statsmodels did that to me and that's why I added the check in urbansim_defaults.  Anyone else have any opinions there?

**Comment by pksohn** [comment]
This sounds good to me. I agree that the new behavior is more predictable. A simulation of `sanfran_urbansim` still works fine under this change, and I'm guessing most active urbansim implementations are getting rid of nans before the `predict()` method like in urbansim_defaults. 

I think we should change the test as you suggest, Fletcher. So the new test asserts that for the row with `nan` as input, the predicted value is `nan` (instead of being dropped). I'll write up a PR if there are no other thoughts.

**Comment by pksohn** [comment]
Fixed in #186.

**Comment by bridwell** [comment]
So, I guess this will cause tests to fail if statsmodels has not been updated to 0.8? Is there anyway to support both?

**Comment by pksohn** [comment]
It will indeed cause the tests to fail in old versions, and that's a good reminder that I should have changed the required version of statsmodels in `setup.py` to be 0.8. 

It would be ideal for tests to be checking against a single expected set of behaviors, especially since previous versions of statsmodels are so old at this point, but we could do a simple version check in the tests. Is there a good reason not to upgrade statsmodels?

**Comment by bridwell** [comment]
I upgraded and the tests now pass. I just ask because anaconda seems to install the 0.6 version by default.. But I suppose changing the setup.py would take care of this.

**Comment by pksohn** [comment]
Great! There might have been a lag with Anaconda getting the latest version on the default channel. We'll leave the test as-is then, and I'll bump statsmodels to 0.8 in `setup.py`.
