### ISSUE TITLE
urbansim using outdated version of pandana

### ISSUE THREAD

**Issue by sablanchard** [UDST/urbansim#214]
urbansim is using outdated version of pandana with `==0.3.0` set inside of `setup.py`. `setup.py` could be updated to use latest version or at least enforce version `>=0.4.0` as pandana API has changed since `0.3.0` but should not impact its use in urbansim.

**Comment by smmaurer** [comment]
Resolved. Pandana was updated in v0.4.2 to run legacy code without errors: https://github.com/UDST/pandana/releases/tag/v0.4.2
